### PR TITLE
feat: make secure flag of cookie configurable

### LINKED ISSUE #15: Unable to parse newly created API key from Headscale
## Overview:

When attempting to connect to a newly instantiated instance of headscale, I am attempting to generate a new API key, as per the instructions from the `/admin` interface. However, when I paste the newly created API key, I am getting an error saying it is unable to be parsed. I have tried using older versions, as well, but that does not seem to fix the issue.

## `docker-compose.yaml`

```yaml
version: '3.8'
services:
  headscale:
    image: 'headscale/headscale:0.23.0-alpha11'
    container_name: 'headscale'
    restart: 'unless-stopped'
    command: 'serve'
    volumes:
      - './data:/var/lib/headscale'
      - './config:/etc/headscale'
    ports:
      - '8081:8080'
      - '9090:9090'
      - '50443:50443'
    environment:
      TZ: 'America/Chicago'

  headplane:
    container_name: headplane
    image: ghcr.io/tale/headplane:latest
    restart: unless-stopped
    volumes:
      - './data:/var/lib/headscale'
      - './config:/etc/headscale'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    ports:
      - '8888:3000'
    environment:
      HEADSCALE_URL: 'http://headscale:8080'
      COOKIE_SECRET: '<redacted>'
      API_KEY: '<redacted>'


      # These are the default values
      HOST: '0.0.0.0'
      PORT: '3000'
```

## Generating API key from Headscale:
```
ash-4.4# docker-compose exec -it headscale headscale apikeys create
2024-05-27T09:55:17-05:00 TRC DNS configuration loaded dns_config={"Nameservers":["9.9.9.9"],"Proxied":true,"Resolvers":[{"Addr":"9.9.9.9"}]}
An updated version of Headscale has been found (0.23.0-alpha9 vs. your current v0.23.0-alpha11). Check it out https://github.com/juanfont/headscale/releases
m92-EDp_-w.ybA6119_PajJHvdZsrw9m6aGAlEdiOVJopDkeIni9w8
```

## Attempting to use the API Key
headplane using new api key

## docker-compose logs from headscale when attempting to use the API key
```
headscale  | 2024-05-27T09:56:11-05:00 ERR home/runner/work/headscale/headscale/hscontrol/app.go:398 > failed to validate token error="failed to parse ApiKey" client_address=172.22.0.3:39080
headplane  | HeadscaleError: Unauthorized
headplane  |     at pull (file:///app/build/server/index.js?t=1716401776000:896:11)
headplane  | GET /admin/machines?_data=routes%2F_data.machines._index 500 - - 10.767 ms
headplane  | GET /admin/login?_data=routes%2Flogin 200 - - 5.428 ms
```

### PR DESCRIPTION
**Pull request by Chihsiao**
Fix #15

### CODE REVIEW

**Comment by tale** [comment]
Would you mind updating the documentation for this?

**Comment by tale** [comment]
Also another nitpick, but what do you think about making the default true? I'd like to push good practices, but if there's even a way to autodetect it that could help or just specify you need to explicitly set it to false.

**Comment by Chihsiao** [comment]
I'm accustomed to setting this option to `false` by default so the program works out of the box, allowing people to get started quickly. If you prefer to set the default to true I have no problem with that.

As for auto-detection, while we can use the `X-Forwarded-Proto` header to determine the endpoint type from a reverse proxy, it's not reliable. We can't guarantee the endpoint is strictly HTTPS or HTTP only, rather than supporting both. When the endpoint is HTTPS only or HTTP only, it works fine, but if both HTTP and HTTPS are supported, it undermines the purpose of `Secure` flag beside making inconsistency.

**Comment by tale** [comment]
Is `X-Forwarded-Proto` automatically supplied by most reverse proxies?

**Comment by Chihsiao** [comment]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto), `X-Forwarded-Proto` is a de-facto standard header. Most modern reverse proxies, like Caddy and Traefik, support it by default without needing additional configuration.

Additionally, nearly all reverse proxy servers, including Nginx and Apache, allow you to modify request headers passed to the upstream, so you can easily enable support for it.

**Review by tale — APPROVED** [review]

**Comment by tale** [comment]
I'll merge it in, but I will change the default to `true` for now. Will definitely look into better ways to support this heuristic automatically in the future.

**Pull request merged**
